baseurl = "https://mtn.github.io/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Michael Noronha"
title = "mtn"
pluralizelisttitles = false

[permalinks]
posts = "posts/:filename/"

[params]
enlarged = true
exclude_headings = ["blog"]
large_banner_logo = true
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Blog and personal website"
logofile = "img/logo.jpg"
faviconfile = "img/favicon.ico"
highlightjs = true
progressively = true
align_left = true
lang = "en"
github = "mtn"
gitlab = "mtn1"
keybase = "mnoronha"
githubRepo = "mtn/hugo-super"
email = "mnoronha@uchicago.edu"
linkedin = "mnoronha"
social_banner = "img/banner.png"
latestpostcount = 3
googleanalytics = "UA-96604723-1"
uselatex = true
disablefancyfonts = false
titlestyle = "lowercase"

